export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const GET_FILTERED_USERTYPE = "GET_FILTERED_USERTYPE";
export const SET_ALERT = " SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_USERS = "GET_USERS";
export const EMAIL_SENT = "EMAIL_SENT";



export const SET_DATE = "SET_DATE";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const GET_ERRORS = "GET_ERRORS";
export const LOAD_QUIZ = "LOAD_QUIZ";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_QUIZ_LOADING = "SET_QUIZ_LOADING";
export const END_FREE_QUIZ = "END_FREE_QUIZ";
export const CLEAR_QUIZ_STATS = "CLEAR_QUIZ_STATS";
export const SET_USER_COLOR = "SET_USER_COLOR";


export const GET_MANUFACTURER = "GET_MANUFACTURER";
export const SET_CURRENT_MANUFACTURER = "SET_CURRENT_MANUFACTURER";
export const GET_MANUFACTURERS = "GET_MANUFACTURERS";
export const ADD_MANUFACTURER = "ADD_MANUFACTURER";
export const FETCH_MANUFACTURER = "FETCH_MANUFACTURER";
export const EDIT_MANUFACTURER = "EDIT_MANUFACTURER";
export const DELETE_MANUFACTURER = "DELETE_MANUFACTURER";
export const MANUFACTURER_ERROR = "MANUFACTURER_ERROR";
export const CLEAR_MANUFACTURER = "CLEAR_MANUFACTURER";



export const GET_ALL_PROCESS = "GET_ALL_PROCESS";
export const SET_CURRENT_ALL_PROCESS = "SET_CURRENT_ALL_PROCESS";
export const GET_ALL_PROCESSES = "GET_ALL_PROCESSES";
export const ADD_ALL_PROCESS = "ADD_ALL_PROCESS";
export const FETCH_ALL_PROCESS = "FETCH_ALL_PROCESS";
export const EDIT_ALL_PROCESS = "EDIT_ALL_PROCESS";
export const DELETE_ALL_PROCESS = "DELETE_ALL_PROCESS";
export const ALL_PROCESS_ERROR = "ALL_PROCESS_ERROR"

export const GET_SPLITTING = "GET_SPLITTING";
export const ADD_SPLITTING = "ADD_SPLITTING";
export const GET_SPLITTINGS = "GET_SPLITTINGS";
export const SET_CURRENT_SPLITTING = "SET_CURRENT_SPLITTING";
export const EDIT_ALL_SPLITTING = "EDIT_SPLITTING";
export const DELETE_SPLITTING = "DELETE_SPLITTING";
export const SPLITTING_ERROR = "SPLITTING_ERROR";
export const GET_SPLITTINGS_QTY = "GET_SPLITTINGS_QTY"
export const GET_MFC_QTY_SPLITTINGS = "GET_MFC_QTY_SPLITTINGS"
export const GET_DAILY_TOTAL_SPLITTINGS = "GET_DAILY_TOTAL_SPLITTINGS"
export const GET_MONTHLY_TOTAL_SPLITTINGS = "GET_MONTHLY_TOTAL_SPLITTINGS"

export const GET_DRYDRUM = "GET_DRYDRUM";
export const ADD_DRYDRUM = "ADD_DRYDRUM";
export const GET_DRYDRUMS = "GET_DRYDRUMS";
export const SET_CURRENT_DRYDRUM = "SET_CURRENT_DRYDRUM";
export const EDIT_ALL_DRYDRUM = "EDIT_DRYDRUM";
export const DELETE_DRYDRUM = "DELETE_DRYDRUM";
export const DRYDRUM_ERROR = "DRYDRUM_ERROR";
export const GET_DRYDRUMS_QTY = "GET_DRYDRUMS_QTY"
export const GET_MFC_QTY_DRYDRUMS = "GET_MFC_QTY_DRYDRUMS"
export const GET_MAP_MFC_DRYDRUMS = "GET_MAP_MFC_DRYDRUMS"




