
export const FILTER_DRYDRUM_RATE = "FILTER_DRYDRUM_RATE";
export const GET_CURRENT_DRYDRUM = "GET_CURRENT_DRYDRUM";
export const SET_CURRENT_RATE_DRYDRUM = "SET_CURRENT_RATE_DRYDRUM";
export const EDIT_RATE_DRYDRUM = "EDIT_RATE_DRYDRUM";
export const DELETE_RATE_DRYDRUM = "DELETE_RATE_DRYDRUM";
export const RATE_DRYDRUM_ERROR = "RATE_DRYDRUM_ERROR";

export const GET_ALL_GLOBAL_PRICES = "GET_ALL_GLOBAL_PRICES"
export const GLOBAL_PRICE_ERROR = "GLOBAL_PRICE_ERROR"
export const SET_CURRENT_GLOBAL_PRICE = "SET_CURRENT_GLOBAL_PRICE"
export const DELETE_GLOBAL_PRICE = "DELETE_GLOBAL_PRICE"
export const GET_CURRENT_GLOBAL_PRICE = "GET_CURRENT_GLOBAL_PRICE"
export const ADD_GLOBAL_PRICE = "ADD_GLOBAL_PRICE"